version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: assesshub-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assesshub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - assesshub-network

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    container_name: assesshub-server
    depends_on:
      - postgres
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/assesshub
      JWT_SECRET_KEY: your_jwt_secret_key_here
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    restart: unless-stopped
    networks:
      - assesshub-network

  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: assesshub-client
    depends_on:
      - server
    environment:
      VITE_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - assesshub-network

networks:
  assesshub-network:
    driver: bridge

volumes:
  postgres_data:
